#Author Adolfo Lara June 29th 2020
###In this exercise, you have sequences for 10 organisms. 
###Your task is to 1) count total A/T/C/G frequencies in each organism; and 2) calculate the CG% for each organism. 


###Input of DNA Sequence
org09 = "GCTTCGATGGATGGATTTATCGATTGACTTAAACCTTGACTGAAGAATCCTAAGCTAGGATTACGATTATTACACGATTATTAGTACCATGAGATCAGAT"
org04 = "AGCGACGGAGCGACGCAGTGCGAGGGACGGAGCCGAGCGCTAGTGGTACATGCATGGACTCGTCCTGCTGCTCGTGCTCGTGCTCCCTGTCATCAGAGGA"
org08 = "TAAACGTCAATTTGCAGTCAGTCAATAGCGTAAATAACTTTGCAATGCGATACGCTAAAAGCAGACAGCGACAGCTTTGCGTCGTCGTCGTCGTCGTTTT"
org05 = "AGGGCGGACCGCCCGGCCCCCGCGCCCCGTGCCTCGCCTGCGCTGGCGGGTCCCGGGCGGCGTGGGTCCCCACCGCAGGCGGCACGCGGCGGGGGGCCCA"
org10 = "TACGCTAGGTCACTCCATCCGAGGGACGCAGGGACAGGAGGGCGCGCCGCCCCCGGGCCGTCCTTGGTGCTCCCGGTTGGGGTGGTGCTGAGGAGCAGCA"
org06 = "TCCCCCGGCGGCCGGGCGGACCCCGGAGTGCGGGCACCCCCCGCGGGCCCGGCCGTGCGCGCGCCGGCCCGGCCCGCGCCCCGGGCCGGGGGCCCGGGGT"
org03 = "TACCACGAGGAGCACGAGTCATCCTAATACTGAATAATATTATTAGTGTCCTAATCCATCAGTAGATGAGTACATCACCTCCTGGGTGCCTGGGTGGTGT"
org02 = "CCTCGGAGGCAGTGCACCGTAGCGCGCGGGCGGCCGGGGGCCCTGCCCGGTGGGGGGGGCCTGGCCTGGTCCCCCGCCCCGGCCCAGGCGAGGCGACCGA"
org01 = "TAACTCAGGACTTTGGGCTCACTAGATGAATGAGTACTACTGCTAGTGGTCATCCTCATCCTCATCCTCCTGACCGAGGACCCAAGGGCGACGCAGTCAT"
org07 = "TTTAAACTCTATACCTAATCCTTTACATTTGTTACATTAAAGATTGCATAAATGACATCAATTCCATTAGTAGATAACTACTACTAAATCGTAAGTCATT"

org = org05

###Question 1: count total A, T, C, G in DNA sequence.
TotA = 0
TotC = 0
TotG = 0
TotT = 0
i = 0
while i < len(org):
	if org[i] == "A":
		TotA = TotA + 1
	elif org[i] == "C":
		TotC = TotC + 1
	elif org[i] == "G":
		TotG = TotG + 1
	elif org[i] == "T":
		TotT = TotT + 1
	i = i + 1

print("Total A's:",TotA, "|Total C's:",TotC, "|Total G's:",TotG,"|Total T's:",TotT)

###Question 2: calculate CG Content.
CGtot = (TotC + TotG)/len(org) * 100
print("CG% is:",CGtot)
 
 
